//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace islami {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("islami.Resource2", typeof(Resource2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحيم
        ///
        ///اللَّهمَّ بِسَطَوَةِ جَبَرُوْتِ قَهْرِكَ وَبِسُرْعَةِ إِغَاثَةِ نَصْرِكَ وَبِغَيْرَتِكَ لاِنْتِهَاكِ حُرُمَاتِكَ وَبِحِمَايَتِكَ لِمَنِ احْتَمَى بَآيَاتِكَ، نَسْأَلُكَ يَا اللَّهُ يا قَرِيبُ يَا سميعُ يَا مُجِيبُ، يا سَرِيعُ يَا جَبَّارُ يَا مُنْتَقِمُ يا قهَّارُ، يَا شَدِيدَ البَطْش، يَا مَنْ لا يُعْجِزُه قَهْرُ الْجَبَابِرَة، وَلا يَعْظُمُ عَلَيْهِ هَلاكُ الْمُتَمَرِّدَةِ مِنَ الْمُلُوكِ وَالأَكَاسِرَةِ، أَنْ تَجْعَلَ كَيْدَ مَنْ كَادَنَي في نَحْرِه وَمَكْرَ مَنْ مَكَرَ بِي عَائِ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nasr {
            get {
                return ResourceManager.GetString("nasr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله  الرحمن الرحيم
        ///
        ///ـ بسم  الله،  الله أكبر، الله  أكبر، الله أكبر، أقول على نفسي وعلى  ديني ، وعلى أهلي  وعلى أولادي وعلى مالي وعلى أصحابي وعلى أديانهم وعلى أموالهم ألف بسم الله، الله أكبر، الله أكبر ، الله أكبر ، أقول عن نفسي 
        ///وعلى ديني وعلى أهلي وعلى أولادي وعلى مالي وعلى أصحابي وعلى أديانهم وعلى أموالهم ألف ألف بسم الله 
        /// الله أكبر، الله أكبر، الله أكبر، أقول على نفسي وعلى ديني وعلى أهلي وعلى أولادي وعلى مالي وعلى أصحابي وعلى أديانهم وعلى أموالهم ألف ألف لاحول ولا قوة إلا بالله العلي العظيم. 
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nawawi {
            get {
                return ResourceManager.GetString("nawawi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرة واحدة : (( أعوذ بالله من الشيطان الرجيم )).
        ///ثلاث مرات : (( بسم الله الرحمن الرحيم )) .
        ///مرة واحدة : ( وَمَا تُقَدِّمُوا لأَنْفُسِكُمْ مِنْ خَيْرٍ تَجِدُوهُ عِنْدَ اللَّهِ هُوَ خَيْرًا وَأَعْظَمَ أَجْرًا وَاسْتَغْفِرُو االلَّهَ إِنَّ اللَّهَ غَفُورٌ رَحِيمٌ ) [المزمل/20] .
        ///(99) مرة : (( أستغفر الله )).
        ///مرة واحدة : (( أستغفر الله العظيم الذي لا إله إلا هو الحي القيوم وأتوب إليه )) .
        ///مرة واحدة : ( إِنَّ اللَّهَ وَمَلائِكَتَهُ يُصَلُّونَ عَلَى النَّبِيِّ يَاأَيُّهَا الَّذِينَ آمَنُوا صَلُّوا عَلَيْهِ وَ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string shazel {
            get {
                return ResourceManager.GetString("shazel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Smoking_is_one_of_the_most_harmful_habits_in_the_world {
            get {
                object obj = ResourceManager.GetObject("Smoking_is_one_of_the_most_harmful_habits_in_the_world", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
